---
- name: Add optional custom apt repositories (for additional zookeeper versions)
  apt_repository: repo={{item.repository_url}} state=present
  when: "{{ ansible_distribution_version|version_compare(item.distro_version, item.version_comparator|default('=')) }}"
  with_items:
    - "{{ zookeeper_debian_apt_repositories }}"

- name: Update apt cache
  apt: update_cache=yes cache_valid_time={{apt_cache_timeout}}
  tags: bootstrap

- name: Apt install required system packages.
  apt:
    pkg: [zookeeper, zookeeperd]
  tags: bootstrap
