---
- name: "Ensure the tarball dir exists at {{ zookeeper_tarball_dir }}"
  file:
    path: "{{ zookeeper_tarball_dir }}"
    state: directory

- name: "Ensure the zookeeper dir exists at {{ zookeeper_dir }}"
  file:
    path: "{{ zookeeper_dir }}"
    state: directory

# If the file exists already, the S3 call can experience errors
- name: check whether the tarball is downloaded already
  stat:
    path: "{{ zookeeper_tarball_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz"
  register: zookeeper_tarball_script

- name: Download zookeeper from S3
  aws_s3:
    mode: get
    bucket: "{{ zookeeper_archive_s3_bucket }}"
    object: "{{ zookeeper_archive_s3_object }}"
    dest: "{{ zookeeper_tarball_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz"
  register: zookeeper_s3_tarball_downloaded
  tags: bootstrap
  when: >
    zookeeper_archive_s3_bucket is defined and
    zookeeper_archive_s3_object is defined and
    not zookeeper_tarball_script.stat.exists

- name: Download zookeeper version.
  get_url:
    url: "{{ zookeeper_url }}"
    dest: "{{ zookeeper_tarball_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz"
  tags: bootstrap
  register: zookeeper_tarball_downloaded
  when: >
    zookeeper_archive_s3_bucket is not defined or
    zookeeper_archive_s3_object is not defined

- name: Unpack tarball.
  command: tar xf {{ zookeeper_tarball_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz --strip-components=1 chdir={{ zookeeper_dir }} creates={{ zookeeper_dir }}/bin
  tags: bootstrap

- name: Ensure group zookeeper exists.
  group:
    name: zookeeper
    system: yes

- name: Ensure user zookeeper exists.
  user:
    name: zookeeper
    group: zookeeper
    system: yes

- name: Change ownership on zookeeper directory.
  file:
    path: "{{ zookeeper_dir }}"
    state: directory
    owner: zookeeper
    group: zookeeper
  tags: bootstrap

- name: Add zookeeper's bin dir to the PATH
  copy:
    content: "export PATH=$PATH:{{ zookeeper_dir }}/bin"
    dest: "/etc/profile.d/zookeeper_path.sh"
    mode: 755
  when: zookeeper_register_path_env
